---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
      solveButton: false
    - name: "02-clientenrollment"
      label: "Clientenrollment"
      solveButton: false
    - name: "03-usermanagement"
      label: "Usermanagement"
      solveButton: false
    - name: "04-hostbasedaccesscontrol"
      label: "Hostbasedaccesscontrol"
      solveButton: false
    - name: "05-sudo"
      label: "Sudo"
      solveButton: false
    - name: "06-selinuxusermaps"
      label: "Selinuxusermaps"
      solveButton: false
    - name: "07-sshkeymanagement"
      label: "Sshkeymanagement"
      solveButton: false

tabs:
  - name: "IdM Primary"
    url: /wetty_idmprimary/ssh/root
    modules: 
      - 01-introduction
      - 02-clientenrollment
      - 03-usermanagement
      - 04-hostbasedaccesscontrol
      - 05-sudo
      - 06-selinuxusermaps
      - 07-sshkeymanagement

  - name: "IdM Client1"
    url: /wetty_idmclient1/ssh/root
    modules: 
      - 01-introduction
      - 02-clientenrollment
      - 03-usermanagement
      - 04-hostbasedaccesscontrol
      - 05-sudo
      - 06-selinuxusermaps
      - 07-sshkeymanagement

# The url line uses the name of the *service* entry from the instance.yaml file
# NOT the hostname/name of the system the name of the server
# remember you are not dealing with hostnames but rather OCP services and routes

  - name: "IdM Web UI"
    url: https://idm-webui-${guid}.${domain}/ipa/ui/

  - name: "RHEL Web Console"
    url: https://cockpit-${guid}.${domain}/
  
