== Welcome to the Identity Management Workshop

=== IMPORTANT: Using this lab

____
This text is in a resizable frame. Some of the commands you will need
are wider than the default area. Use your mouse to grab the resize bar
that separates the text from the terminal window and resize the these
contents for comfortable viewing.

Some of the commands that you need to execute in the terminal window are
provided to you for convenience. They are listed in a code formatted
area. Hover over the right side of the area with your mouse to reveal
the copy button. Click to copy all the text to the clipboard. See the
example below.
____

[source,bash]
----
echo "I copied this text using the copy button here >>>"
----

____
Expected output is from commands in the terminal window are displayed as
code. These sections do not provide a copy button.
____

With that, let’s look at our environment.

=== Environment

The lab environment will consist of the following systems:

* 1 Red Hat Identity Management (IdM) server
* 1 IdM client

You are logged into the consoles with root access by the environment. A
local user account has also been created that you can use:

This user is a member of wheel and has sudo access.

You can preform all of the activities in the labs using the root
account. The above account has been provided should it become necessary.

*To prepare for the lab, please execute the following command:*

[source,bash]
----
/root/labsetup.sh
----

This command simply updates our local hosts file with the private ip of
our cloud instance.

=== Exercise 1.1 - Install the IdM server

The IdM server binaries are provided in the ipa-server package. It is
delivered as a modular component in Red Hat Enterprise Linux 8 and 9.
The ipa-server package has been installed on the idmserver1 system
within your environment during creation.

The configuration of the IdM server managed by an installer program. We
add the *–no-host-dns* parameter to support our lab environment. In a
production environment, to ensure proper DNS delegation, DNS forwarding,
etc.. checking the host dns entry ensures that our configuration will
function as expected. The *–mkhomedir* option is used to ensure that PAM
creates missing home directories for users when they login for the first
time. IdM also supports automount for those use cases where oddjobd and
automount use is authorized.

During the installation of the IdM server you will be asked a number of
questions. Please accept the defaults *unless outlined below*.

Using the *IdM Server* tab, start by running the installation command:

[source,bash]
----
sudo ipa-server-install --no-host-dns --mkhomedir
----

To support our kerberos realm, we want the IdM server to manage our DNS
for us. You are asked whether to configure integrated DNS.

Answer *yes*

This ensures that the installer configures the underlying standard RHEL
BIND implementation.

Kerberos is tightly tied to DNS as clients use DNS for kerberos service
discovery. In a DNS zone, there is only one kerberos authority allowed.
The service entries for kerberos accept multiple values, however, all
systems must belong to the same realm. If there is an Active Directory
service running in the same DNS domain we will have a conflict. User and
system authentication will randomly fail as there are multiple
authorities discovered through DNS. IdM servers and AD servers must
belong to separate DNS domains. Typically, AD DNS services delegate to
IdM servers for the IdM domain. DNS for the IdM realm can be managed
external to the IdM servers, however, the same restriction applies and
Active Directory DNS or the DNS supporting AD must delgate
appriopriately.

The next series of prompts ask you to verify the installer discovered
values for the server hostname, domain name and realm. Accept the
default by pressing enter after each of the following questions.

You will need to provide a password for the *LDAP Directory Manager* and
for the *IdM admin* account. It requires a minimum of 8 characters. For
both, please use:

[source,bash]
----
redhat2024
----

There are several more questions related to the DNS configuration,
NETBIOS name, and time servers.

Accept the default or type yes.

Accept the default found by the search of resolv.conf by pressing Enter
or typing yes.

Accept the default or type yes. You should get a message stating that it
already exists.

Next, you will see a message similar to the following asking for the
NETBIOS name of the *IPA Domain* (not the IPA server):

Accept the default or type yes.

Time servers are already configured by the environment. Accept the
default or type *no*.

You will then be prompted to confirm that you wish to proceed with the
installation using the stated configuration.

This is the "`Are you sure?`" moment. You need to type in *yes* here.

The installation should take about 5-10 minutes. Follow the remainder of
the installation process and examine the output.

The installation will: * Configure a stand-alone CA (dogtag) for
certificate management * Configure the NTP client (chronyd) * Create and
configure an instance of Directory Server * Create and configure a
Kerberos Key Distribution Center (KDC) * Configure Apache (httpd) *
Configure SID generation * Configure the KDC to enable PKINIT * Install
and configure the IdM client software

Once setup is complete, you will presented with a *Next Steps* section.

Please examine these and take note of the firewall ports that are
required to be open to the IdM Server system.

=== Exercise 1.2 - Examine the firewall settings

From a host-based firewall prespective (always recommended), the network
ports have been setup for you as part of the lab preparation using
firewalld. You can examine the configuration with firewall-cmd. Red Hat
provides preconfigured service settings for easily enabling the
appropriate ports for IdM. Running list-services, you should see a list
similar to the following:

[source,bash]
----
firewall-cmd --list-services
----

To investigate what is controlled by each service listing, run a command
similar to the following:

[source,bash]
----
firewall-cmd --info-service freeipa-ldaps
----

[source,bash]
----
firewall-cmd --info-service freeipa-4
----

For information on why these ports are required and how they are used,
please see the Identity Management documentation.

=== Exercise 1.3 - Verify the installation.

Verify that you can authenticate with the new IdM realm using the
default admin user and the password you provided.

[source,bash]
----
kinit admin@[[ Instruqt-Var key="realm" hostname="idmserver1" ]]
----

____
NOTE: you can omit the realm name as it will be setup as a default in
/etc/krb5.conf If you wish, you can investigate these settings by
reviewing the file. Do not make changes.
____

Run klist to verify your authenitication token.

[source,bash]
----
klist
----

Verify all the components of the server are up and running.

[source,bash]
----
ipactl status
----

Verify the health of the server.

....
ipa-healthcheck
....

A fully-functioning IdM installation returns an empty result of [].

In the latest versions of IdM, DNS recursion has been disabled as
appropriate. We will ensure that trusted connections on our local
network can use our DNS server to resolve domains not served by our DNS.
Run the following setup script to add our trusted networks to the proper
configuration files.

[source,bash]
----
/root/trustednetwork.sh
----

This adds an entry to the named configuration for IdM DNS
(/etc/named/ipa-ext.conf) to identify the trusted networks similar to
the following.

It also sets up the recursion, caching and dnssec options in the IdM
named options configuration (/etc/named/ipa-options-ext.conf).

Restart the IdM services to ensure that the configuration is applied.
The ipactl command is used to manage the IdM services.

[source,bash]
----
ipactl restart
----

Verify DNS resolution for connected clients.

[source,bash]
----
nslookup cdn.redhat.com
----

You should see the records come back for the local akamai edge network
server replicating the CDN content.

We are now ready to register client systems!
