== Welcome to the Identity Management Workshop

=== Module 1: Introduction

*IMPORTANT: Using this lab*

This text is in a resizable frame. Some of the commands you will need are wider than the default area.
Use your mouse to grab the resize bar that separates the text from the terminal window and resize the these contents for comfortable viewing.

Some of the commands that you need to execute in the terminal window are provided to you for convenience.
They are listed in a code formatted area.
On the right side of the code formatted area there are a couple of buttons.
The first button copies all the text to the clipboard.
The second botton actually executes the code in the terminal.
When possible, try to type and execute the code yourself.
It helps with learning.
If you are having trouble, by all means, click away!
See the example below.

[source,bash]
----
echo "I copied this text using the copy button here >>>"
----

Expected output from commands in the terminal window are also displayed as code.

With that, let’s look at our environment.

==== Environment

The lab environment will consist of the following systems:

* 1 x Red Hat Identity Management (IdM) Primary server - idmprimary
* 1 x Red Hat Identity Management (IdM) Replica server - idmreplica
* 2 x IdM clients - idmclient1, idmclient2

For most purposes, an IdM Primary server and an IdM Replica server are identical, the only difference being the order of installation. 
In more sophisticated installations, we can configure servers to perform different roles to streamline Identity Management processing and operational workflow.
For our first environment, the will be identical to support full redundancy of services as we have only 2 systems. 
Identity Management environments can support as many as 64 replicas in a mesh like configuration. 
Services may be distributed to optimize replication 

For module 1, we will only be working at the idmprimary system.
There are additional tabs on the right side of the screen to allow you additional interaction if necessary.
One tab, is labelled for the idmprimary and one for idmclient1.
You are logged into the consoles with root access by the environment.
A local user account has also been created that you can use:

[source,bash,subs="+macros,+attributes",role=execute]
----
username: rhel
password: {bastion_ssh_password}
----

This user is a member of wheel and has sudo access.

You can preform all of the activities in the labs using the root account.
The above account has been provided should it become necessary.
Throughout the workshop we will create a variety of other users.
The instructions will be clear as to what operations are to be performed using a specific login.

==== Let's get started
=== Exercise 1.1 - Install the IdM server

The IdM server binaries are provided in the ipa-server package. 
The ipa-server package has been installed on the idmprimary system within your environment during provisioning.

The configuration of the IdM server managed by an installer program.
We add the *--no-host-dns* parameter to support our lab environment.
In a production environment, to ensure proper DNS delegation, DNS forwarding, etc.. checking the host dns entry ensures that our configuration will function as expected. 
The *--mkhomedir* option is used to ensure that PAM creates missing home directories for users when they login for the first time.
IdM also supports automount for those use cases where oddjobd and automount use is authorized.

During the installation of the IdM server you will be asked a number of questions.
Please accept the defaults *unless outlined below*.

Using the *IdM Primary* tab, start by running the installation command:

[source,bash]
----
sudo ipa-server-install --no-host-dns --mkhomedir
----

To support our kerberos realm, we want the IdM server to manage our DNS for us.
You are asked whether to configure integrated DNS.

Answer *yes*

This ensures that the installer configures the underlying standard RHEL BIND implementation.

Kerberos is tightly tied to DNS as clients use DNS for kerberos service discovery.
In a DNS zone, there is only one kerberos authority allowed.
The service entries for kerberos accept multiple values, however, all systems must belong to the same realm.
If there is an Active Directory service running in the same DNS domain we will have a conflict.
User and system authentication will randomly fail as there are multiple authorities discovered through DNS.
IdM servers and AD servers must belong to separate DNS domains.
Typically, AD DNS services delegate to IdM servers for the IdM domain.
DNS for the IdM realm can be managed external to the IdM servers, however, the same restriction applies and Active Directory DNS or the DNS supporting AD must delgate appriopriately.

The next series of prompts ask you to verify the installer discovered values for the server hostname, domain name and realm.
Accept the default by pressing enter after each of the following questions.

You will need to provide a password for the *LDAP Directory Manager* and for the *IdM admin* account.
It requires a minimum of 8 characters. 
*For both, please use:*

[source,bash]
----
redhat2026
----

There are several more questions related to the DNS configuration, NETBIOS name, and time servers.
*Accept the default or type yes.*

First the setup tries to determine if forwarding is necessary, pressing *Enter* or typing *yes* to search for forwarders.
----
Checking DNS domain lab.sandbox-hwlcf-zt-rhelbu.svc.cluster.local., please wait ...
No network interface matches the IP address 10.130.9.240
WARNING: No network interface matches the IP address 10.130.9.240
Do you want to configure DNS forwarders? [yes]: 
----

It will come back with the entry from resolv.conf. Accept the default or type yes. 

----
Do you want to configure these servers as DNS forwarders? [yes]:
----

You can add additional forwarders in by typing them at the prompt.
Just press enter to continue without entering any additional forwarders.

----
All detected DNS servers were added. You can enter additional addresses now:
Enter an IP address for a DNS forwarder, or press Enter to skip:
----

The system validates the forwarders and then asks to search for reverse zones.
Search for reverse zones by accepting the default or typing yes.

----
DNS forwarders: 172.30.0.10
Checking DNS forwarders, please wait ...
Do you want to search for missing reverse zones? [yes]:
----

Accept the discovered reverse zones.

Next, you will see a message similar to the following asking for the NETBIOS name of the *IPA Domain* (not the IPA server):
Accept the default or type yes.

Time synchronization is already configured by the environment. 
Accept the default or type *no*.

You will then be prompted to confirm that you wish to proceed with the installation using the stated configuration.

This is the "`Are you sure?`" moment. You need to type in *yes* here.

The installation should take about 5-10 minutes. Follow the remainder of the installation process and examine the output.

The installation will:

* Configure a stand-alone CA (dogtag) for certificate management 
* Configure the NTP client (chronyd)
* Create and configure an instance of Directory Server 
* Create and configure a Kerberos Key Distribution Center (KDC)
* Configure Apache (httpd) 
* Configure SID generation
* Configure the KDC to enable PKINIT
* Install and configure the IdM client software

Once setup is complete, you will presented with a *Next Steps* section.

Please examine these and take note of the firewall ports that are required to be open to the IdM Server system.

=== Exercise 1.2 - Examine the firewall settings

From a host-based firewall prespective (always recommended), the network ports have been setup for you as part of the lab preparation using firewalld.
You can examine the configuration with firewall-cmd.
Red Hat provides preconfigured service settings for easily enabling the appropriate ports for IdM.
Running list-services, you should see a list similar to the following:

[source,bash]
----
firewall-cmd --list-services
----

To investigate what is controlled by each service listing, run a command similar to the following:

[source,bash]
----
firewall-cmd --info-service freeipa-ldaps
----

[source,bash]
----
firewall-cmd --info-service freeipa-4
----

For information on why these ports are required and how they are used, please see the Identity Management documentation.

=== Exercise 1.3 - Verify the installation.

Verify that you can authenticate with the new IdM realm using the default admin user and the password you provided.

[source,bash]
----
kinit admin
----


NOTE: you can omit the realm name as it will be setup as a default in /etc/krb5.conf If you wish, you can investigate these settings by reviewing the file. Do not make changes.

Run klist to verify your authenitication token.

[source,bash]
----
klist
----

Verify all the components of the server are up and running.

[source,bash]
----
ipactl status
----

Verify the health of the server.

....
ipa-healthcheck
....

A fully-functioning IdM installation returns an empty result of [].
In our environment you may see a permissions error on a file in /var
This is a known issue and can be safely ignored at this time.

In the latest versions of IdM, DNS recursion has been disabled as appropriate.
We will ensure that trusted connections on our local network can use our DNS server to resolve domains not served by our DNS.
Run the following setup script to add our trusted networks to the proper configuration files.

[source,bash]
----
/root/trustednetwork.sh
----

This adds an entry to the named configuration for IdM DNS (/etc/named/ipa-ext.conf) to identify the trusted networks similar to the following.

It also sets up the recursion, caching and dnssec options in the IdM named options configuration (/etc/named/ipa-options-ext.conf).

Restart the IdM services to ensure that the configuration is applied.
The ipactl command is used to manage the IdM services.

[source,bash]
----
ipactl restart
----

Verify DNS resolution for connected clients.

[source,bash]
----
nslookup cdn.redhat.com
----

You should see the records come back for the local akamai edge network server replicating the CDN content.

Lastly, if we are allowing new systems DNS to be registered, we want to make sure that we allow reverse records to be syncrhonised automatically.
This is done either through the Web UI, which we will look at later, or through the ipa CLI.

[source,bash]
----
ipa dnsconfig-mod --allow-sync-ptr=true
----

The result should look something like the following:

[source]
----
  Allow PTR sync: True
  IPA DNS servers: idmprimary.example.local
----

We are now ready to register client systems!
