== Welcome to Module 6

=== SELinux User Maps
==== SELinux basics

SELinux is a mandatory access controls mechanism for Linux, providing more powerful and flexible access control than traditional Unix permissions.
For a complete overview of SELinux please work with your Red Hat account team to schedule an SELinux policy workshop.

For a Red Hat Enterprise Linux system, there are two elements in _/etc/selinux/config_ that control primary SELinux configuration :
- SELINUX - one of enforcing, permissive or disabled, and;
- SELINUXTYPE - targeted, minimum, or mls (Multi Level Security)

SELinux is enabled by default on all Red Hat Enterprise Linux installations.
All modern software certifications for RHEL (since RHEL7), regardless of vendor, are only certified with SELinux configured for enforcing + targeted.
It is *strongly* recommended that all systems maintain the default configuration unless a *higher* level of security is required. (i.e. don't turn it off, please)

All ojects in Red Hat Enterprise, including users, have an SELinux context consisting of 4 context elements: a user (u), role (r), type (t) and sensitivity (s) values.
Multi-Level Security SELinux uses the sensitivity element in addition to a category (c) element. 
We will not be discussing Multi-Level Security with SELinux in the lab. 
For non-MLS SELinux (default), the sensitivity is typically set to s0. 

When a user is created or logs in to a RHEL system, they are assigned something called an SELinux Role. This defines the default context for that user on that system.
As with other aspects of security, it is very beneficial to manage this centrally for production deployments.
This gives us better visibility, enhanced consistency and allows more streamlined configuration across a fleet of RHEL systems.

No surprise then that Identity Management provides a mechanism for us to manage SELinux policy across the IdM realm.

==== What you will learn in this Lab

In this unit, you will cause users to be _confined_ by an SELinux _role-based access control (RBAC) policy_ when the log into hosts that are members of the _webservers_ Host Group. You will also learn how to _change a user's SELinux context_ when they execute commands via sudo.

*Note:* SELinux contexts are applied during PAM-based login, so when testing our changes in this unit _su -l <user>_ *will not* suffice: it is necessary to log in via SSH.
You can do this from any of the VMs.

=== Exercise 6.1 - Examining SELinux policy and Confining users

Virtually all commands in RHEL include a -Z option to display the SELinux context. 

As an example, for our user *_alice_*, you can display the context by entering:

[source,bash]
----
[alice@idmclient1] id -Z
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
----

*_alice_* is currently *_unconfined_*. We want her to be confined to the _staff_u_ context when she logs in, to limit the impact of an account compromise.
Think of staff_u as a context that we give administrative users so that they can perform administrative function, but they run in a secure, restricted context to prevent accidental system damage. 
They are restricted from using *_su_* to become root and are limited in their ability to perform operations directly in the system_u context.
They are requireed to use secure and logged mething to get elevated privilege.

SELinux User Maps can refer to users and hosts directly, or they can inherit the users and hosts of an existing HBAC rule.
Since access control to a system is defined by HBAC, it is a good administration practice to link SELinux User Maps to HBAC rules.
This ensures that when users or hosts are added to the HBAC rule, the correct SELinux context will automatically be used.
Sweet.

Back in module 4, we created the *_sysadmin_webservers_* HBAC rule that allows members of the sysadmin User Group to have access to systems in the *_webservers_* host group.
We can create a new SELinux user map by using the following:

[source,bash]
----
ipa selinuxusermap-add sysadmin_staff_t \
    --hbacrule sysadmin_webservers --selinuxuser staff_u:s0-s0:c0.c1023
----

The result looks like this:
----
-----------------------------------------
Added SELinux User Map "sysadmin_staff_t"
-----------------------------------------
  Rule name: sysadmin_staff_t
  SELinux User: staff_u:s0-s0:c0.c1023
  HBAC Rule: sysadmin_webservers
  Enabled: TRUE
----

To test this, we have to login to the system as *_alice_* via ssh.

[source,bash]
----
ssh alice@idmclient1.example.local
----

Determine the SELinux user context for *_alice_*

[source,bash]
----
id -Z
----

Your result should show:

----
[idmprimary]$ ssh alice@idmclient1.example.local
alice@idmclient1.example.local's password:
Last login: Fri Feb 13 15:47:03 2026

[alice@client]$ id -Z
staff_u:staff_r:staff_t:s0-s0:c0.c1023
----

*NOTE:* *WARNING* In production, ensure that only one HBAC rule allows access for a given *user + host + SELinux User Map* combination.
Only one SELinux policy will be applied to a user for on login.
If there are multiple policy matches for a given *user + host + SELinux User Map* combination the winning policy may be chosen inconsistently.

=== Exercise 6.2 - Unconfined ``sudo`` 
==== When is root, not really root?

*_alice_* is now *_confined_* by the ``staff_u`` policy, but being a sysadmin she needs to be unconfined when running commands via sudo.
With the current configuration, commands run via ``sudo`` inherit her user's context, as the following commands demonstrate:

----
[alice@client]$ sudo -s
[sudo] password for alice:

sh-4.4# id
uid=0(root) gid=0(root) groups=0(root) context=staff_u:staff_r:staff_t:s0-s0:c0.c1023

sh-4.4# echo "Hello, world!" > /etc/motd
sh: /etc/motd: Permission denied
----

Try this on your own to verify.

As you can see, user *_alice_* became root, but the SELinux confinement prevents her from writing /etc/motd (and many other things).
Let's make it so that Alice can do her job.
We need to update the sudo rule to change the SELinux context using the following commands:

[source,bash]
----
ipa sudorule-add-option sysadmin_sudo --sudooption type=unconfined_t
----

The result of the previous command should look like:
----
-------------------------------------------------------------
Added option "type=unconfined_t" to Sudo Rule "sysadmin_sudo"
-------------------------------------------------------------
  Rule name: sysadmin_sudo
  Enabled: TRUE
  Host category: all
  Command category: all
  RunAs User category: all
  RunAs Group category: all
  Sudo Option: type=unconfined_t
----

[source,bash]
----
ipa sudorule-add-option sysadmin_sudo --sudooption role=unconfined_r
----

The result of the previous command should look like:
----
-------------------------------------------------------------
Added option "role=unconfined_r" to Sudo Rule "sysadmin_sudo"
-------------------------------------------------------------
  Rule name: sysadmin_sudo
  Enabled: TRUE
  Host category: all
  Command category: all
  RunAs User category: all
  RunAs Group category: all
  Sudo Option: type=unconfined_t, role=unconfined_r
----

Now when *_alice_* runs sudo it *_changes the SELinux context of the program_* being run:

[source,bash]
----
sudo -s
----

[source,bash]
----
id -Z
----

We should see:
----
staff_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
----

Now lets try to modify the Message of the day again.

[source,bash]
----
echo "Hello, world!" > /etc/motd
----

[source,bash]
----
cat /etc/motd
----

We see:
----
Hello, world!
----

Alice now has the proper SELinux context when she runs sudo commands to allow her to execute her administrative commands.


This concludes the module 6.

==== What we learned

- SELinux policy can be controlled centrally using Identity Management
- SELinux policy can be appropriately bound to both Host Based Access Control policy and sudo policy
- How to add an SELinux user map for an Identity Management group.
- How to link that SELinux user map to a previously created HBAC policy
- How to link that SELinux user map to a previously created sudo policy

Let's look at managining SSH keys centrally next.
