=== Welcome to Module 10
==== Service Certificate Management

You probably noticed that the web service was not hosted over HTTPS, so there is no TLS-based authentication or confidentiality.
In this unit, we will issue an X.509 certificate for the web service via the Certmonger program.

Certmonger supports multiple CAs including Identity Management CA.

Certmonger can:

- generate key pairs
- generate certificate signing requests
- request the certificates from an authority
- track the certificate's expiration dates, and
- renew tracked certificates when the expiration time approaches

It can also use mod_ssl with Apache.

=== Exercise 10.1 - Issue the service certificate

Let's start by confirming that the HTTP service for our app does not yet have a certificate:

[source,bash]
----
ipa service-show HTTP/idmclient2.example.local
----

----
  Principal name: HTTP/client.ipademo.local@IPADEMO.LOCAL
  Principal alias: HTTP/client.ipademo.local@IPADEMO.LOCAL
  Keytab: True
  Managed by: client.ipademo.local
----

Now let's enable and start the Certmonger service:

[source,bash]
----
sudo systemctl enable --now certmonger
----

----
Created symlink /etc/systemd/system/multi-user.target.wants/certmonger.service → /usr/lib/systemd/system/certmonger.service.
----

Now let's request a certificate.
We will generate keys and store certificates in the NSS database at /etc/httpd/alias:

[source,bash]
----
sudo ipa-getcert request \
  -I idmclient2_web_service \
  -f /etc/pki/tls/certs/app.crt \
  -k /etc/pki/tls/private/app.key \
  -K HTTP/idmclient2.example.local \
  -D idmclient2.example.local
----

----
New signing request "20260215185400" added.
----

Let's break down some of those command arguments.

-I <string> - this is the identity of the request, if you don't provide it a timestamp is generated as the id, names are better for remembering what is being tracked

-k <path> - Path to private key (Certmonger will generate it)

-f <path> - Path to certificate (where it will be saved after being issued)

-K <principal> - Kerberos service principal; because different kinds of services may be accessed at one hostname, this argument tells Certmonger which service principal is the subject

-D <dnsname> - Requests the given domain name to appear in the Subject Alternative Name (SAN) extension; today the Common Name (CN) field is no longer used by browsers so the SAN value is essential

Another important option is -N <subject-name>. It defaults to the system hostname, which in our case (idmclient2.example.local) is appropriate.


Let's check the status of our certificate request using the tracking identifier given in the ipa-getcert request output:

[source,bash]
----
sudo ipa-getcert list -i idmclient2_web_service
----

----
Number of certificates and requests being tracked: 1.
Request ID 'idmclient2_web_service':
  status: MONITORING
  stuck: no
  key pair storage: type=FILE,location='/etc/pki/tls/private/app.key'
  certificate: type=FILE,location='/etc/pki/tls/certs/app.crt'
  CA: IPA
  issuer: CN=Certificate Authority,O=EXAMPLE.LOCAL
  subject: CN=idmclient2.example.local,O=EXAMPLE.LOCAL
  expires: 2027-02-13 20:54:00 UTC
  dns: idmclient2.example.local
  principal name: HTTP/idmclient2.example.local@EXAMPLE.LOCAL
  key usage: digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment
  eku: id-kp-serverAuth,id-kp-clientAuth
  pre-save command:
  post-save command:
  track: yes
  auto-renew: yes
----

Confirm that the certificate was issued and that Certmonger is now MONITORING the certificate and will auto-renew it when it is close to expiration.
Now if you run ipa service-show, you will see a number of attributes related to the certificate, including the certificate itself.
Can you work out how to save the PEM-encoded certificate to a file?


=== Exercise 10.2 - Set up TLS for Apache

Now we can reconfigure Apache to serve our app over TLS.
Update app.conf to listen on port 443 and add the SSL directives:

[source,bash]
----
sudo vim /etc/httpd/conf.d/app.conf
----

----
...

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile "/etc/pki/tls/certs/app.crt"
    SSLCertificateKeyFile "/etc/pki/tls/private/app.key"
    ServerName idmclient2.example.local

    WSGIScriptAlias / /usr/share/httpd/app.py

    <Location />
        AuthType GSSAPI
        AuthName "Kerberos Login"
        GssapiCredStore keytab:/etc/httpd/app.keytab
        Require pam-account app
        LookupUserAttr mail REMOTE_USER_MAIL
        LookupUserAttr givenname REMOTE_USER_FIRSTNAME
        LookupUserAttr sn REMOTE_USER_LASTNAME
        LookupUserGroupsIter REMOTE_USER_GROUP
    </Location>

    <Directory /usr/share/httpd>
        <Files "app.py">
            Require all granted
        </Files>
    </Directory>
</VirtualHost>
----

Restart Apache and make a request to the app over HTTPS:

[source,bash]
----
sudo systemctl restart httpd
curl -u : --negotiate https://idmclient2.example.local
----

----
LOGGED IN AS: alice@EXAMPLE.LOCAL

REMOTE_* REQUEST VARIABLES:

  REMOTE_USER: alice@EXAMPLE.LOCAL
  REMOTE_USER_GROUP_1: ipausers
  REMOTE_USER_GROUP_2: sysadmins
  REMOTE_USER_GROUP_N: 2
  REMOTE_USER_FIRSTNAME: Alice
  REMOTE_USER_LASTNAME: Armstrong
  REMOTE_USER_MAIL: alice@example.local
  REMOTE_ADDR: 192.168.33.20
  REMOTE_PORT: 51876
----

We are now managing our site with a certificate that is monitored and centrally managed by IdM and our web service system will automatically ask it to be renewed as it approaches expiration date.

