---
virtualmachines:
  - name: "idmprimary"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
    services:
      - name: idmprimary-webui
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: idmprimary-webui
      - name: idmp-ldap-389-tcp
        ports:
          - port: 389
            protocol: TCP
            targetPort: 389
            name: idmp-ldap-389-tcp
      - name: idmp-ldaps-636-tcp
        ports:
          - port: 636
            protocol: TCP
            targetPort: 636
            name: idmp-ldap-636-tcp
      - name: idmp-kerberos-88-tcp
        ports:
          - port: 88
            protocol: TCP
            targetPort: 88
            name: idmp-kerberos-88-tcp
      - name: idmp-kerberos-464-tcp
        ports:
          - port: 464
            protocol: TCP
            targetPort: 464
            name: idmp-kerberos-464-tcp
      - name: idmp-kerberos-88-udp
        ports:
          - port: 88
            protocol: UDP
            targetPort: 88
            name: idmp-kerberos-88-udp
      - name: idmp-kerberos-464-udp
        ports:
          - port: 464
            protocol: UDP
            targetPort: 464
            name: idmp-kerberos-464-udp
      - name: idmp-dns-53-tcp
        ports:
          - port: 53
            protocol: TCP``
            targetPort: 53
            name: idmp-dns-53-tcp
      - name: idmp-dns-53-udp
        ports:
          - port: 53
            protocol: UDP
            targetPort: 53
            name: idmp-dns-53-udp


    routes:
      - name: idmprimary-webui
        host: idmprimary
        service: idmprimary-webui
        targetPort: 443
      - name: idmp-ldap-389-tcp
        host: idmprimary
        service: idmp-ldap-389-tcp
        targetPort: 389
      - name: idmp-ldaps-636-tcp
        host: idmprimary
        service: idmp-ldaps-636-tcp
        targetPort: 636
      - name: idmp-keberos-88-tcp
        host: idmprimary
        service: idmp-keberos-88-tcp
        targetPort: 88
      - name: idmp-keberos-464-tcp
        host: idmprimary
        service: idmp-keberos-464-tcp
        targetPort: 464
      - name: idmp-keberos-88-udp
        host: idmprimary
        service: idmp-keberos-88-udp
        targetPort: 88
      - name: idmp-keberos-464-udp
        host: idmprimary
        service: idmp-keberos-464-udp
        targetPort: 464
      - name: idmp-dns-53-tcp
        host: idmprimary
        service: idmp-dns-53-tcp
        targetPort: 53
      - name: idmp-dns-53-udp
        host: idmprimary
        service: idmp-dns-53-udp
        targetPort: 53

  - name: "idmreplica"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
    services:
      - name: idm2
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: idm2
    routes:
      - name: idm2
        host: idmreplica
        service: idm2
        targetPort: 443

  - name: "idmclient1"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - cockpit
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    # services:
    #   - name: cockpit
    #     ports:
    #       - port: 9090
    #         protocol: TCP
    #         targetPort: 9090
    #         name: cockpit
    # routes:
    #   - name: cockpit
    #     host: idmclient1
    #     service: cockpit
    #     targetPort: 9090
    #     tls: true
    #     tls_termination: Edge

  - name: "idmclient2"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - cockpit
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
