---
virtualmachines:
  - name: "idmprimary"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
    services:
      - name: idmprimary_webui
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: idmprimary_webui
      # - name: idmp_ldap_389_tcp
      #   ports:
      #     - port: 389
      #       protocol: TCP
      #       targetPort: 389
      #       name: idmp_ldap_389_tcp
      # - name: idmp_ldaps_636_tcp
      #   ports:
      #     - port: 636
      #       protocol: TCP
      #       targetPort: 636
      #       name: idmp_ldap_636_tcp
      # - name: idmp_kerberos_88_tcp
      #   ports:
      #     - port: 88
      #       protocol: TCP
      #       targetPort: 88
      #       name: idmp_kerberos_88_tcp
      # - name: idmp_kerberos_464_tcp
      #   ports:
      #     - port: 464
      #       protocol: TCP
      #       targetPort: 464
      #       name: idmp_kerberos_464_tcp
      # - name: idmp_kerberos_88_udp
      #   ports:
      #     - port: 88
      #       protocol: UDP
      #       targetPort: 88
      #       name: idmp_kerberos_88_udp
      # - name: idmp_kerberos_464_udp
      #   ports:
      #     - port: 464
      #       protocol: UDP
      #       targetPort: 464
      #       name: idmp_kerberos_464_udp
      # - name: idmp_dns_53_tcp
      #   ports:
      #     - port: 53
      #       protocol: TCP``
      #       targetPort: 53
      #       name: idmp_dns_53_tcp
      # - name: idmp_dns_53_udp
      #   ports:
      #     - port: 53
      #       protocol: UDP
      #       targetPort: 53
      #       name: idmp_dns_53_udp


    routes:
      - name: idmprimary_webui
        host: idmprimary
        service: idmprimary_webui
        targetPort: 443
      # - name: idmp_ldap_389_tcp
      #   host: idmprimary
      #   service: idmp_ldap_389_tcp
      #   targetPort: 389
      # - name: idmp_ldaps_636_tcp
      #   host: idmprimary
      #   service: idmp_ldaps_636_tcp
      #   targetPort: 636
      # - name: idmp_keberos_88_tcp
      #   host: idmprimary
      #   service: idmp_keberos_88_tcp
      #   targetPort: 88
      # - name: idmp_keberos_464_tcp
      #   host: idmprimary
      #   service: idmp_keberos_464_tcp
      #   targetPort: 464
      # - name: idmp_keberos_88_udp
      #   host: idmprimary
      #   service: idmp_keberos_88_udp
      #   targetPort: 88
      # - name: idmp_keberos_464_udp
      #   host: idmprimary
      #   service: idmp_keberos_464_udp
      #   targetPort: 464
      # - name: idmp_dns_53_tcp
      #   host: idmprimary
      #   service: idmp_dns_53_tcp
      #   targetPort: 53
      # - name: idmp_dns_53_udp
      #   host: idmprimary
      #   service: idmp_dns_53_udp
      #   targetPort: 53

  - name: "idmreplica"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
    services:
      - name: idm2
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: idm2
    routes:
      - name: idm2
        host: idmreplica
        service: idm2
        targetPort: 443

  - name: "idmclient1"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - cockpit
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    # services:
    #   - name: cockpit
    #     ports:
    #       - port: 9090
    #         protocol: TCP
    #         targetPort: 9090
    #         name: cockpit
    # routes:
    #   - name: cockpit
    #     host: idmclient1
    #     service: cockpit
    #     targetPort: 9090
    #     tls: true
    #     tls_termination: Edge

  - name: "idmclient2"
#    image: "rhel-10-0-07-09-25-3"
    image: "rhel-9.6"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - cockpit
      - tmux
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
